lunar_craters = [
    { name: "Copernicus", diameter: 93, unit_of_measure: "km", location: "9.62°N 20.08°W" },
    { name: "Tycho", diameter: 85, unit_of_measure: "km", location: "43.31°S 11.36°W" },
    { name: "Aristarchus", diameter: 40, unit_of_measure: "km", location: "23.73°N 47.49°W" },
    { name: "Kepler", diameter: 32, unit_of_measure: "km", location: "8.1°N 38.0°W" },
    { name: "Plato", diameter: 101, unit_of_measure: "km", location: "51.6°N 9.3°W" },
    { name: "Clavius", diameter: 225, unit_of_measure: "km", location: "58.4°S 14.4°W" },
    { name: "Archimedes", diameter: 83, unit_of_measure: "km", location: "29.7°N 4.0°W" },
    { name: "Gassendi", diameter: 110, unit_of_measure: "km", location: "17.5°S 39.9°W" },
    { name: "Ptolemaeus", diameter: 153, unit_of_measure: "km", location: "9.3°S 1.9°W" },
    { name: "Alphonsus", diameter: 118, unit_of_measure: "km", location: "13.4°S 3.2°W" },
    { name: "Eratosthenes", diameter: 58, unit_of_measure: "km", location: "14.5°N 11.3°W" },
    { name: "Grimaldi", diameter: 173, unit_of_measure: "km", location: "5.2°S 68.3°W" },
    { name: "Humboldt", diameter: 207, unit_of_measure: "km", location: "27.0°S 80.9°E" },
    { name: "Langrenus", diameter: 132, unit_of_measure: "km", location: "8.9°S 60.9°E" },
    { name: "Petavius", diameter: 177, unit_of_measure: "km", location: "25.1°S 60.4°E" },
    { name: "Schickard", diameter: 227, unit_of_measure: "km", location: "44.3°S 54.6°W" },
    { name: "Theophilus", diameter: 101, unit_of_measure: "km", location: "11.4°S 26.4°E" },
    { name: "Mare Crisium", diameter: 556, unit_of_measure: "km", location: "17.0°N 59.1°E" },
    { name: "Mare Imbrium", diameter: 1145, unit_of_measure: "km", location: "32.8°N 15.6°W" },
    { name: "Mare Serenitatis", diameter: 674, unit_of_measure: "km", location: "27.4°N 17.6°E" },
    { name: "Mare Tranquillitatis", diameter: 873, unit_of_measure: "km", location: "8.5°N 31.4°E" },
    { name: "Proclus", diameter: 28, unit_of_measure: "km", location: "16.1°N 47.0°E" },
    { name: "Posidonius", diameter: 95, unit_of_measure: "km", location: "31.8°N 29.9°E" },
    { name: "Janssen", diameter: 190, unit_of_measure: "km", location: "45.4°S 40.8°E" },
    { name: "Vendelinus", diameter: 147, unit_of_measure: "km", location: "16.8°S 61.3°E" },
    { name: "Albategnius", diameter: 131, unit_of_measure: "km", location: "11.2°S 4.1°E" }
]

