# tools/test_migration.rb
# Usage: Run this script from the root of your project directory using:
# bin/rails r tools/test_migration.rb
#
# This script simulates the minimal environment needed to run the service
# and tests the migration of a single legacy material file (e.g., acetylene).

require 'json'
require 'fileutils'
require 'pathname'
require 'logger'
# Load ActiveSupport dependency for String#titleize
require 'active_support/core_ext/string/inflections'


# --- 1. MOCK RAILS ENVIRONMENT (Minimal necessary definition) ---
module Rails
  def self.root
    Pathname.new(File.expand_path('.'))
  end
  def self.logger
    @logger ||= Logger.new($stdout).tap { |l| l.level = Logger::INFO }
  end
end
Rails.logger.level = Logger::INFO 


# --- 2. CRITICAL REQUIRES ---
# We must load the paths and service using relative paths from the tools/ directory.
require_relative '../app/paths'
require_relative '../app/services/material_generator_service' 


# --- 3. EXPLICITLY DEFINE MOCK CLASS TO PREVENT NameError ---
# The service relies on this mock class for migration/enrichment
class GameDataGenerator
  def initialize(**args)
    Rails.logger.info "MOCK: Initializing GameDataGenerator (Dependency-free mock loaded)."
  end
  
  # This method mocks the LLM enrichment API call.
  def generate_item(template_path, output_path, params)
    Rails.logger.warn "MOCK: LLM enrichment triggered for #{params['id']}. Returning mocked v1.2 data."
    mock_enriched_data = {
      "template" => "material",
      "id" => params['id'],
      "name" => params['name'],
      "description" => "A highly enriched material based on legacy context, generated by SCRIPT MOCK.",
      "category" => params['category'],
      "subcategory" => "industrial_gas",
      "metadata" => { "version" => "1.2", "type" => "material", "source_mock" => "LLM" },
      "trade_value" => 150,
      "properties" => { "state_at_room_temp" => "Gas", "unit_of_measurement" => "m3" },
      "composition" => [{"element" => "Carbon", "atoms" => 2}, {"element" => "Hydrogen", "atoms" => 2}],
      "applications" => ["Welding", "Synthesis"],
      "production" => {"method" => "Thermal Cracking", "efficiency" => 0.8},
      "requirements" => {"technology" => ["High-pressure vessel"], "facilities" => ["Chemical plant"]},
      "pricing" => {"base_cost" => 50, "volatility" => "High"}
    }
    return mock_enriched_data
  end
end


# --- 4. SETUP: Create Mock Directories and Legacy File ---
TEST_DIR = Rails.root.join('app', 'data', 'json-data')
LEGACY_PATH = TEST_DIR.join('old-json-data', 'production_old4', 'materials')
MATERIAL_ID = 'acetylene'
LEGACY_FILE = LEGACY_PATH.join("#{MATERIAL_ID}.json")
FINAL_FILE = nil

# Calculate the expected final path for cleanup
# NOTE: We use the service's logic to determine the relative path string, 
# then join it to the service's BASE_DIR constant for the full path.
MOCK_LEGACY_DATA = { "category" => "gas", "id" => MATERIAL_ID }
EXPECTED_RELATIVE_PATH = MaterialGeneratorService.determine_save_path(MOCK_LEGACY_DATA)
PRE_TEST_CLEANUP_PATH = MaterialGeneratorService::BASE_DIR.join(EXPECTED_RELATIVE_PATH)


# Ensure test paths exist
FileUtils.mkdir_p(LEGACY_PATH)
FileUtils.mkdir_p(MaterialGeneratorService::BASE_DIR)

# --- 5. PRE-TEST CLEANUP ---
# Ensure the final file doesn't exist before running the migration
if File.exist?(PRE_TEST_CLEANUP_PATH)
  FileUtils.rm_f(PRE_TEST_CLEANUP_PATH)
  Rails.logger.info "Cleaned up old final file: #{PRE_TEST_CLEANUP_PATH}"
end


# Create the mock legacy file
LEGACY_CONTENT = {
    "id": "acetylene",
    "name": "Acetylene",
    "category": "gas",
    "type": "raw_material",
    "subtype": "industrial_gas",
    "chemical_formula": "C2H2",
    "description": "A flammable gas used in welding and cutting.",
}.to_json

File.write(LEGACY_FILE, LEGACY_CONTENT)
Rails.logger.info "Setup complete. Created mock legacy file at: #{LEGACY_FILE}"

# --- 6. EXECUTION ---
Rails.logger.info "--- STARTING MIGRATION TEST ---"
begin
  # Call the class method directly, which handles loading, migrating, and saving.
  migrated_data = MaterialGeneratorService.generate_material(MATERIAL_ID)

  Rails.logger.info "--- MIGRATION COMPLETE ---"
  
  if migrated_data
    # Use the pre-calculated path which points to the correct location via BASE_DIR
    FINAL_FILE = PRE_TEST_CLEANUP_PATH 
    
    Rails.logger.info "Expected Final Save Path: #{FINAL_FILE}"
    
    if File.exist?(FINAL_FILE)
      Rails.logger.info "TEST SUCCESS: Final v1.2 file saved to: #{FINAL_FILE}"
      
      # Read the file content to ensure it was saved correctly
      saved_content = JSON.parse(File.read(FINAL_FILE))

      Rails.logger.info "Final Content Sample (Read from disk):"
      Rails.logger.info JSON.pretty_generate(saved_content)[0..300] + "..."
      
      # Assertions
      if saved_content.dig("metadata", "version") == "1.2"
        Rails.logger.info "TEST PASS: Version is correctly set to 1.2."
      else
        Rails.logger.error "TEST FAIL: Version is NOT 1.2 (found #{saved_content.dig("metadata", "version")})."
      end
      
      if saved_content.key?("production") && saved_content.key?("composition")
        Rails.logger.info "TEST PASS: LLM enrichment (production/composition fields) is present."
      else
        Rails.logger.error "TEST FAIL: LLM enrichment missing key fields (production/composition)."
      end
      
    else
      Rails.logger.error "TEST FAIL: File was NOT saved to the expected location: #{FINAL_FILE}"
    end
  else
    Rails.logger.error "TEST FAIL: Migration returned nil data."
  end

rescue => e
  Rails.logger.error "An error occurred during migration: #{e.message}"
  Rails.logger.error e.backtrace.join("\n")
ensure
  # --- 7. CLEANUP ---
  Rails.logger.info "--- CLEANING UP ---"
  FileUtils.rm_f(LEGACY_FILE)
  if FINAL_FILE && File.exist?(FINAL_FILE)
     FileUtils.rm_f(FINAL_FILE)
     Rails.logger.info "Removed final migrated file: #{FINAL_FILE}"
  end
  Rails.logger.info "Cleanup complete. Test environment is restored."
end